user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

holigo:
    resource: "@holigoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
